--- #YAML:1.0
name:                POE-Component-WWW-YouTube-VideoURI
version:             0.03
abstract:            Non-blocking L<POE> wrapper around
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::Entities:                1.35
    LWP::UserAgent:                2.036
    POE:                           0.9999
    POE::Filter::Line:             1.192
    POE::Filter::Reference:        1.2187
    POE::Wheel::Run:               1.2179
    WWW::YouTube::VideoURI:        0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
