---
name: POE-Component-WWW-YouTube-VideoURI
version: 0.06
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  Non-blocking L<POE> wrapper around
  WWW::YouTube::VideoURI with download abilities.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  HTML::Entities: 1.35
  LWP::UserAgent: 2.036
  POE: 0.9999
  POE::Filter::Line: 1.192
  POE::Filter::Reference: 1.2187
  POE::Wheel::Run: 1.2179
  WWW::YouTube::VideoURI: 0.1
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::YouTube::VideoURI:
    file: lib/POE/Component/WWW/YouTube/VideoURI.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
